### PR TITLE
Added specs for requests

### PR DESCRIPTION
**Pull request by damdafayton**
- Add RSpec as a gem to your project.
- Create a Request spec file for all your controllers.
- Make sure that for each action you check:
    - If response status was correct.
    - If a correct template was rendered.
    - If the response body includes correct placeholder text.

### CODE REVIEW

**Review by SajjadAhmad14 — CHANGES_REQUESTED** [review]
```markdown
Hi Yucel, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not follow Git flow. Please make the `develop` branch the default branch. You may learn more about Git flow [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

Invalid Code Review Request **does not count** into the code reviews limit._
```

**Comment by damdafayton** [comment]
> ```gfm
> Hi Yucel, 
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> 
> You have submitted a project, that does not follow Git flow. Please make the `develop` branch the default branch. You may learn more about Git flow [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> --------
> 
> Invalid Code Review Request **does not count** into the code reviews limit._
> ```
@SajjadAhmad14 
PR is into dev branch. It does conform to the gitflow. I didn't understand why you claim otherwise.

**Comment by SajjadAhmad14** [comment]
Hi,

Kindly learn about Git flow from the link I already provided. Git flow uses ' dev ' branch as default. But your project uses '  main ' branch as default branch.

**Comment by damdafayton** [comment]
> Hi,
> 
> Kindly learn about Git flow from the link I already provided. Git flow uses ' dev ' branch as default. But your project uses ' main ' branch as default branch.

I know what is git flow. It's my 6th month. Despite main being default PR is into the 'dev', which means I merged into `dev` consciously.

I just forgot to set default to dev, which doesn't require the rejection. You could have made a review and I could still change the default.

**Review by mikethreels — APPROVED** [review]
Hi Yucel, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
